# Generated by Django 3.2.12 on 2022-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vaccine', models.TextField()),
                ('total_vaccinations', models.IntegerField()),
            ],
        ),
    ]
