# Generated by Django 3.2.12 on 2022-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0002_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='total_vaccinations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='daily_vaccinations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.TextField(),
        ),
    ]
